### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by velolib** [velolib/gregtech-flow#7]
# Overview
This is the roadmap for GT: Flow. Starts at 117f7abc98804888948ed12d947b090cf14b2a5a
# Towards 1.0.0
- [ ] Make schema for projects
- [ ] Gallery section in website
- [ ] Faster font loading in website
- [ ] Allow CLI to parse multiple projects somehow
- [ ] Add linter to actions
- [ ] Switch to parenthesis instead of brackets
- [ ] Fix ticks format in final graph
- [ ] Documentation for [output], [recycle], etc.
- [ ] Fix multi IO
- [ ] Switch to using absolute paths when using DCLI
- [ ] Find minimum python version
- [ ] Add option in ICLI to print file tree
# Future
- Fix 1-tick machines
- Make use of the project header metadata somehow
- Standardize object naming
- Use svg as a standard then convert to other formats to fix unicode fonts
